### ISSUE TITLE
ioctl() command 35585 (0x8b01) is not found

### ISSUE THREAD

**Issue by mengrj** [GJDuck/RRFuzz#2]
There is one error about `ioctl` missing. 

> error: 2628308: ioctl() command 35585 (0x8b01) is not found in "ioctl.tab"

**Comment by agatah2333** [comment]
Hello, I'm getting the following error: "ioctl() command 35142 (0x8946) is not found in "ioctl.tab"". May I know how to resolve this?

**Comment by GJDuck** [comment]
Basically, you need to Google what the ioctl number `0x8946` means, then add an appropriate entry to `ioctl.tab`.

There are thousands of ioctls, so we only have added entries for the common ones.  If your program-under-test uses a new ioctl, then you may need to add an entry yourself.

The `0x8946` number corresponds to `SIOCETHTOOL` which apparently "queries or controls network driver and hardware settings".  You can also try adding the following line to `ioctl.tab`, which will simply cause the ioctl to fail during recording:

        SIOCETHTOOL         0x8946          fail      0
